### PR TITLE
Updated for Python3 compatibility

### PR DESCRIPTION
**Pull request by ghost**
I have updated pylzss.c and test.py to now work with Python3. I also incremented the version number in setup.py.

### CODE REVIEW

**Comment by yyogo** [comment]
Hey, unfortunately this only works on Python 3 and not on 2...

**Comment by ghost** [comment]
@rumbah I have fixed it to be compatible with both major versions.

**Comment by ghost** [comment]
Ok, there should be a #define for the python version. I will fix it tonight.

**Comment by yyogo** [comment]
Thanks, I've already included [py3c](https://github.com/encukou/py3c) which makes compatibility simpler. Will push it soon.

**Pull request merged**
